"""Generates the mobile app's design tokens from DESIGN.md's front matter.

DESIGN.md is the one home for colours, type scale, radii and spacing; the website
mirrors it in CSS and this writes the Dart copy, so the app never hand-copies a value.

    make mobile-tokens
    (= cd backend && uv run python ../tools/mobile/gen_tokens.py ../DESIGN.md \
         ../mobile/lib/theme/tokens.g.dart)
"""

from __future__ import annotations

import re
import sys

import yaml

TYPES = [
    "normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison", "ground",
    "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark", "steel", "fairy",
]


def camel(name: str) -> str:
    head, *rest = re.split(r"[-_ ]", name)
    return head + "".join(w[:1].upper() + w[1:] for w in rest)


def color(value: str) -> str:
    v = str(value).strip()
    if m := re.fullmatch(r"#([0-9a-fA-F]{6})", v):
        return f"Color(0xFF{m[1].upper()})"
    if m := re.fullmatch(r"rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)", v):
        r, g, b, a = int(m[1]), int(m[2]), int(m[3]), float(m[4])
        return f"Color(0x{round(a * 255):02X}{r:02X}{g:02X}{b:02X})"
    raise ValueError(f"unsupported colour {value!r}")


def px(value) -> float | None:
    """A length in logical px (rem × 16); None for values the app can't use (clamp())."""
    v = str(value).strip()
    if m := re.fullmatch(r"([\d.]+)px", v):
        return float(m[1])
    if m := re.fullmatch(r"([\d.]+)rem", v):
        return float(m[1]) * 16
    return None


def num(x: float) -> str:
    return f"{x:g}" if "." in f"{x:g}" else f"{x:g}.0"


def text_style(spec: dict) -> str:
    family = spec["fontFamily"].split(",")[0].strip()
    size = px(spec["fontSize"])
    parts = [f"fontFamily: '{family}'", f"fontSize: {num(size)}"]
    parts.append(f"fontWeight: FontWeight.w{int(spec['fontWeight'])}")
    if "lineHeight" in spec:
        parts.append(f"height: {num(float(spec['lineHeight']))}")
    if ls := spec.get("letterSpacing"):
        em = float(str(ls).removesuffix("em"))
        parts.append(f"letterSpacing: {num(round(em * size, 4))}")
    return "TextStyle(" + ", ".join(parts) + ")"


def generate(design_md: str) -> str:
    front = yaml.safe_load(design_md.split("---")[1])
    colors: dict = front["colors"]
    out = [
        "// GENERATED by tools/mobile/gen_tokens.py from DESIGN.md — don't edit by hand.",
        "// Run `make mobile-tokens` after changing DESIGN.md.",
        "",
        "import 'package:flutter/painting.dart';",
        "",
        "/// Every colour in DESIGN.md, by its name there (camelCased).",
        "abstract final class Palette {",
    ]
    for name, value in colors.items():
        out.append(f"  static const {camel(name)} = {color(value)};")
    out += [
        "}",
        "",
        "/// Type colours: fill (chips, bars), on (text on a fill), text (type name as text).",
        "abstract final class TypeColors {",
    ]
    for role, suffix in (("fill", ""), ("on", "-on"), ("text", "-text")):
        entries = []
        for t in TYPES:
            key = f"type-{t}{suffix}"
            if (value := colors.get(key)) is None:
                raise KeyError(f"DESIGN.md has no {key}")
            entries.append(f"    '{t}': {color(value)},")
        out += [f"  static const {role} = <String, Color>{{", *entries, "  };"]
    out += ["}", "", "abstract final class Radii {"]
    for name, value in front["rounded"].items():
        out.append(f"  static const {camel(name)} = {num(px(value))};")
    out += ["}", "", "abstract final class Space {"]
    for name, value in front["spacing"].items():
        if (v := px(value)) is not None:
            out.append(f"  static const {camel(name)} = {num(v)};")
    out += ["}", "", "/// The type scale (font sizes in logical px; letter spacing from em).",
            "abstract final class TypeScale {"]
    for name, spec in front["typography"].items():
        out.append(f"  static const {camel(name)} = {text_style(spec)};")
    out += ["}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "../DESIGN.md"
    dst = sys.argv[2] if len(sys.argv) > 2 else "../mobile/lib/theme/tokens.g.dart"
    with open(src) as f:
        code = generate(f.read())
    with open(dst, "w") as f:
        f.write(code)
    print(f"wrote {dst}")
