"""pokemon training and breeding fields

Revision ID: 3b865352aed5
Revises: ced6136903f8
Create Date: 2026-09-09 11:22:23.824165
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3b865352aed5'
down_revision: str | None = 'ced6136903f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('gender_rate', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('hatch_counter', sa.Integer(), nullable=True))
    op.add_column('pokemon', sa.Column('growth_rate', sa.String(length=32), nullable=True))
    op.add_column('pokemon', sa.Column('egg_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pokemon', sa.Column('ev_yield', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'ev_yield')
    op.drop_column('pokemon', 'egg_groups')
    op.drop_column('pokemon', 'growth_rate')
    op.drop_column('pokemon', 'hatch_counter')
    op.drop_column('pokemon', 'gender_rate')
    # ### end Alembic commands ###
