"""pokemon_form per-form data

Revision ID: 72f70233db46
Revises: f5a1c3d7b204
Create Date: 2026-09-20 23:25:28.767067
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72f70233db46'
down_revision: str | None = 'f5a1c3d7b204'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'pokemon_forms',
        sa.Column(
            'flavor_texts',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        'pokemon_forms',
        sa.Column(
            'learnset',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column('pokemon_forms', sa.Column('evolves_from_form_id', sa.Integer(), nullable=True))
    op.add_column('pokemon_forms', sa.Column('evo_trigger', sa.String(length=64), nullable=True))
    op.add_column('pokemon_forms', sa.Column('evo_min_level', sa.Integer(), nullable=True))
    op.add_column('pokemon_forms', sa.Column('evo_item', sa.String(length=64), nullable=True))
    op.add_column('pokemon_forms', sa.Column('evo_condition', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon_forms', 'evo_condition')
    op.drop_column('pokemon_forms', 'evo_item')
    op.drop_column('pokemon_forms', 'evo_min_level')
    op.drop_column('pokemon_forms', 'evo_trigger')
    op.drop_column('pokemon_forms', 'evolves_from_form_id')
    op.drop_column('pokemon_forms', 'learnset')
    op.drop_column('pokemon_forms', 'flavor_texts')
    # ### end Alembic commands ###
