"""user profile, favorites, question log

Revision ID: 8c0376fdef5a
Revises: 9900ffd8a069
Create Date: 2026-09-08 16:20:56.132630
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c0376fdef5a'
down_revision: str | None = '9900ffd8a069'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_log_created_at'), 'question_log', ['created_at'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('preferred_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    # NOTE: the auto-generated drop of knowledge_chunks.content_tsv / its GIN index
    # was removed — that column is a DB-managed generated tsvector (Phase 6 FTS)
    # intentionally not mapped on the ORM model.
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('user_favorites')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_question_log_created_at'), table_name='question_log')
    op.drop_table('question_log')
    # ### end Alembic commands ###
