"""initial pokemon schema

Revision ID: 92223db1caee
Revises: 
Create Date: 2026-09-08 15:28:40.383857
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '92223db1caee'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('genus', sa.String(length=128), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('capture_rate', sa.Integer(), nullable=True),
    sa.Column('base_happiness', sa.Integer(), nullable=True),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('is_baby', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('shape', sa.String(length=32), nullable=True),
    sa.Column('habitat', sa.String(length=32), nullable=True),
    sa.Column('evolution_chain_id', sa.Integer(), nullable=True),
    sa.Column('evolves_from_species_id', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('sp_attack', sa.Integer(), nullable=False),
    sa.Column('sp_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('base_stat_total', sa.Integer(), nullable=False),
    sa.Column('flavor_text', sa.Text(), nullable=True),
    sa.Column('sprite_path', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_attack'), 'pokemon', ['attack'], unique=False)
    op.create_index(op.f('ix_pokemon_base_stat_total'), 'pokemon', ['base_stat_total'], unique=False)
    op.create_index(op.f('ix_pokemon_defense'), 'pokemon', ['defense'], unique=False)
    op.create_index(op.f('ix_pokemon_dex_number'), 'pokemon', ['dex_number'], unique=False)
    op.create_index(op.f('ix_pokemon_evolution_chain_id'), 'pokemon', ['evolution_chain_id'], unique=False)
    op.create_index(op.f('ix_pokemon_generation_id'), 'pokemon', ['generation_id'], unique=False)
    op.create_index(op.f('ix_pokemon_habitat'), 'pokemon', ['habitat'], unique=False)
    op.create_index(op.f('ix_pokemon_hp'), 'pokemon', ['hp'], unique=False)
    op.create_index(op.f('ix_pokemon_is_legendary'), 'pokemon', ['is_legendary'], unique=False)
    op.create_index(op.f('ix_pokemon_is_mythical'), 'pokemon', ['is_mythical'], unique=False)
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    op.create_index(op.f('ix_pokemon_sp_attack'), 'pokemon', ['sp_attack'], unique=False)
    op.create_index(op.f('ix_pokemon_sp_defense'), 'pokemon', ['sp_defense'], unique=False)
    op.create_index(op.f('ix_pokemon_species_id'), 'pokemon', ['species_id'], unique=False)
    op.create_index(op.f('ix_pokemon_speed'), 'pokemon', ['speed'], unique=False)
    op.create_table('pokemon_abilities',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id', 'slot')
    )
    op.create_table('pokemon_evolutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evolution_chain_id', sa.Integer(), nullable=False),
    sa.Column('from_pokemon_id', sa.Integer(), nullable=True),
    sa.Column('to_pokemon_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.Column('condition', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['from_pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['to_pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evolution_from_to', 'pokemon_evolutions', ['from_pokemon_id', 'to_pokemon_id'], unique=False)
    op.create_index(op.f('ix_pokemon_evolutions_evolution_chain_id'), 'pokemon_evolutions', ['evolution_chain_id'], unique=False)
    op.create_index(op.f('ix_pokemon_evolutions_from_pokemon_id'), 'pokemon_evolutions', ['from_pokemon_id'], unique=False)
    op.create_index(op.f('ix_pokemon_evolutions_to_pokemon_id'), 'pokemon_evolutions', ['to_pokemon_id'], unique=False)
    op.create_table('pokemon_flavor_texts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('flavor_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pokemon_id', 'version', name='uq_flavor_pokemon_version')
    )
    op.create_index(op.f('ix_pokemon_flavor_texts_pokemon_id'), 'pokemon_flavor_texts', ['pokemon_id'], unique=False)
    op.create_table('pokemon_types',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_types')
    op.drop_index(op.f('ix_pokemon_flavor_texts_pokemon_id'), table_name='pokemon_flavor_texts')
    op.drop_table('pokemon_flavor_texts')
    op.drop_index(op.f('ix_pokemon_evolutions_to_pokemon_id'), table_name='pokemon_evolutions')
    op.drop_index(op.f('ix_pokemon_evolutions_from_pokemon_id'), table_name='pokemon_evolutions')
    op.drop_index(op.f('ix_pokemon_evolutions_evolution_chain_id'), table_name='pokemon_evolutions')
    op.drop_index('ix_evolution_from_to', table_name='pokemon_evolutions')
    op.drop_table('pokemon_evolutions')
    op.drop_table('pokemon_abilities')
    op.drop_index(op.f('ix_pokemon_speed'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_species_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_sp_defense'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_sp_attack'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_is_mythical'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_is_legendary'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_hp'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_habitat'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_generation_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_evolution_chain_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_dex_number'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_defense'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_base_stat_total'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_attack'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_table('types')
    op.drop_table('generations')
    op.drop_table('abilities')
    # ### end Alembic commands ###
