"""type effectiveness chart

Revision ID: ced6136903f8
Revises: 8c0376fdef5a
Create Date: 2026-09-09 01:45:08.388351
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ced6136903f8'
down_revision: str | None = '8c0376fdef5a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_effectiveness',
    sa.Column('damage_type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['damage_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('damage_type_id', 'target_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_effectiveness')
    # ### end Alembic commands ###
