// GENERATED by tools/mobile/gen_tokens.py from DESIGN.md — don't edit by hand.
// Run `make mobile-tokens` after changing DESIGN.md.

import 'package:flutter/painting.dart';

/// Every colour in DESIGN.md, by its name there (camelCased).
abstract final class Palette {
  static const pokeballRed = Color(0xFFD8310C);
  static const pokeballRedText = Color(0xFFC42B08);
  static const brandMarkRed = Color(0xFFE3350D);
  static const emberRed = Color(0xFFFF5A34);
  static const verdictGreen = Color(0xFF2FAE6A);
  static const verdictGreenText = Color(0xFF1F7A47);
  static const cautionAmber = Color(0xFFF0B429);
  static const cautionAmberText = Color(0xFF94600A);
  static const youBlue = Color(0xFF2F6BFF);
  static const youBlueText = Color(0xFF2A5FE0);
  static const instrumentInk = Color(0xFF14171D);
  static const inkDim = Color(0xFF3F4650);
  static const mutedSlate = Color(0xFF5F6773);
  static const faintSlate = Color(0xFF666E7B);
  static const panelWhite = Color(0xFFFFFFFF);
  static const insetGray = Color(0xFFF4F5F8);
  static const ground = Color(0xFFEEF0F4);
  static const hairline = Color(0x1A14171D);
  static const hairlineSoft = Color(0x0E14171D);
  static const typeNormal = Color(0xFFA8A878);
  static const typeFire = Color(0xFFF0803C);
  static const typeWater = Color(0xFF5AA0E6);
  static const typeElectric = Color(0xFFF4CF46);
  static const typeGrass = Color(0xFF6FC25A);
  static const typeIce = Color(0xFF8FD4D4);
  static const typeFighting = Color(0xFFD13B52);
  static const typePoison = Color(0xFFB25EC4);
  static const typeGround = Color(0xFFE0C068);
  static const typeFlying = Color(0xFF8AA0E6);
  static const typePsychic = Color(0xFFF0619A);
  static const typeBug = Color(0xFF9FC02F);
  static const typeRock = Color(0xFFB8A038);
  static const typeGhost = Color(0xFF7A5AA0);
  static const typeDragon = Color(0xFF7A5CF0);
  static const typeDark = Color(0xFF5A5366);
  static const typeSteel = Color(0xFFA8B0C0);
  static const typeFairy = Color(0xFFF0A6D0);
  static const typeNormalOn = Color(0xFFFFFFFF);
  static const typeFireOn = Color(0xFFFFFFFF);
  static const typeWaterOn = Color(0xFFFFFFFF);
  static const typeElectricOn = Color(0xFFFFFFFF);
  static const typeGrassOn = Color(0xFFFFFFFF);
  static const typeIceOn = Color(0xFFFFFFFF);
  static const typeFightingOn = Color(0xFFFFFFFF);
  static const typePoisonOn = Color(0xFFFFFFFF);
  static const typeGroundOn = Color(0xFFFFFFFF);
  static const typeFlyingOn = Color(0xFFFFFFFF);
  static const typePsychicOn = Color(0xFFFFFFFF);
  static const typeBugOn = Color(0xFFFFFFFF);
  static const typeRockOn = Color(0xFFFFFFFF);
  static const typeGhostOn = Color(0xFFFFFFFF);
  static const typeDragonOn = Color(0xFFFFFFFF);
  static const typeDarkOn = Color(0xFFFFFFFF);
  static const typeSteelOn = Color(0xFFFFFFFF);
  static const typeFairyOn = Color(0xFFFFFFFF);
  static const typeNormalText = Color(0xFF787749);
  static const typeFireText = Color(0xFFBC570C);
  static const typeWaterText = Color(0xFF3178BB);
  static const typeElectricText = Color(0xFF8A7102);
  static const typeGrassText = Color(0xFF338618);
  static const typeIceText = Color(0xFF397E7E);
  static const typeFightingText = Color(0xFFD13B52);
  static const typePoisonText = Color(0xFFA552B7);
  static const typeGroundText = Color(0xFF8F7105);
  static const typeFlyingText = Color(0xFF5E72B5);
  static const typePsychicText = Color(0xFFCB3E7A);
  static const typeBugText = Color(0xFF667D08);
  static const typeRockText = Color(0xFF887306);
  static const typeGhostText = Color(0xFF7A5AA0);
  static const typeDragonText = Color(0xFF795AEE);
  static const typeDarkText = Color(0xFF5A5366);
  static const typeSteelText = Color(0xFF6D7584);
  static const typeFairyText = Color(0xFFA25F87);
}

/// Type colours: fill (chips, bars), on (text on a fill), text (type name as text).
abstract final class TypeColors {
  static const fill = <String, Color>{
    'normal': Color(0xFFA8A878),
    'fire': Color(0xFFF0803C),
    'water': Color(0xFF5AA0E6),
    'electric': Color(0xFFF4CF46),
    'grass': Color(0xFF6FC25A),
    'ice': Color(0xFF8FD4D4),
    'fighting': Color(0xFFD13B52),
    'poison': Color(0xFFB25EC4),
    'ground': Color(0xFFE0C068),
    'flying': Color(0xFF8AA0E6),
    'psychic': Color(0xFFF0619A),
    'bug': Color(0xFF9FC02F),
    'rock': Color(0xFFB8A038),
    'ghost': Color(0xFF7A5AA0),
    'dragon': Color(0xFF7A5CF0),
    'dark': Color(0xFF5A5366),
    'steel': Color(0xFFA8B0C0),
    'fairy': Color(0xFFF0A6D0),
  };
  static const on = <String, Color>{
    'normal': Color(0xFFFFFFFF),
    'fire': Color(0xFFFFFFFF),
    'water': Color(0xFFFFFFFF),
    'electric': Color(0xFFFFFFFF),
    'grass': Color(0xFFFFFFFF),
    'ice': Color(0xFFFFFFFF),
    'fighting': Color(0xFFFFFFFF),
    'poison': Color(0xFFFFFFFF),
    'ground': Color(0xFFFFFFFF),
    'flying': Color(0xFFFFFFFF),
    'psychic': Color(0xFFFFFFFF),
    'bug': Color(0xFFFFFFFF),
    'rock': Color(0xFFFFFFFF),
    'ghost': Color(0xFFFFFFFF),
    'dragon': Color(0xFFFFFFFF),
    'dark': Color(0xFFFFFFFF),
    'steel': Color(0xFFFFFFFF),
    'fairy': Color(0xFFFFFFFF),
  };
  static const text = <String, Color>{
    'normal': Color(0xFF787749),
    'fire': Color(0xFFBC570C),
    'water': Color(0xFF3178BB),
    'electric': Color(0xFF8A7102),
    'grass': Color(0xFF338618),
    'ice': Color(0xFF397E7E),
    'fighting': Color(0xFFD13B52),
    'poison': Color(0xFFA552B7),
    'ground': Color(0xFF8F7105),
    'flying': Color(0xFF5E72B5),
    'psychic': Color(0xFFCB3E7A),
    'bug': Color(0xFF667D08),
    'rock': Color(0xFF887306),
    'ghost': Color(0xFF7A5AA0),
    'dragon': Color(0xFF795AEE),
    'dark': Color(0xFF5A5366),
    'steel': Color(0xFF6D7584),
    'fairy': Color(0xFFA25F87),
  };
}

abstract final class Radii {
  static const chip = 6.0;
  static const inset = 8.0;
  static const control = 10.0;
  static const card = 14.0;
  static const pill = 99.0;
}

abstract final class Space {
  static const xs = 6.0;
  static const sm = 10.0;
  static const md = 14.0;
  static const lg = 18.0;
  static const gutter = 16.0;
}

/// The type scale (font sizes in logical px; letter spacing from em).
abstract final class TypeScale {
  static const display = TextStyle(fontFamily: 'Chakra Petch', fontSize: 35.2, fontWeight: FontWeight.w600, height: 1.02, letterSpacing: -0.352);
  static const headline = TextStyle(fontFamily: 'Space Grotesk', fontSize: 18.0, fontWeight: FontWeight.w600, height: 1.2, letterSpacing: -0.18);
  static const title = TextStyle(fontFamily: 'Space Grotesk', fontSize: 16.0, fontWeight: FontWeight.w700, height: 1.2, letterSpacing: -0.16);
  static const body = TextStyle(fontFamily: 'Space Grotesk', fontSize: 15.0, fontWeight: FontWeight.w400, height: 1.55);
  static const bodySmall = TextStyle(fontFamily: 'Space Grotesk', fontSize: 13.0, fontWeight: FontWeight.w400, height: 1.5);
  static const label = TextStyle(fontFamily: 'Space Grotesk', fontSize: 12.5, fontWeight: FontWeight.w600, height: 1.4);
  static const readout = TextStyle(fontFamily: 'JetBrains Mono', fontSize: 11.5, fontWeight: FontWeight.w700, height: 1.4, letterSpacing: 0.23);
}
